Company/urls.py
from django.conf.urls import url, include

from .views import *

# Application Routes (URLs)

app_name = 'Company'

urlpatterns = [
    	# General Page Views
		url(r'^homepage/$', CompanyHomepage.as_view(), name='homepage'),
]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^auth/', include('core.urls')),
	url(r'', include('website.urls')),
	url(r'^company/', include('Company.urls')),
]

core/urls.py
from django.conf.urls import url

from . import views

# Application Routes (URLs)

app_name = 'core'

urlpatterns = [

	# Login
	url(r'^login/$', views.login, name='login'),

	# Logout
	url(r'^logout/$', views.logout, name='logout'),
]

website/urls.py
from django.conf.urls import url, include

from . import views

# Application Routes (URLs)

app_name = 'website'

urlpatterns = [
    	# General Page Views
		url(r'^$', views.homepage_view, name='homepage'),
]

Company/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Company(models.Model):
    class Meta:
        verbose_name_plural = "companies"
        
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, default=1, on_delete=models.CASCADE, related_name='employees')
    is_owner = models.BooleanField(default=False)

class Client(models.Model):
    class Meta:
        unique_together = (('company', 'name'),)

    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='clients')
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100, unique=True)
    address = models.CharField(max_length=200)

class Product(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField(default=0)

class Package(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='packages')
    items = models.ManyToManyField('Invoice.Item')

Invoice/models.py
from django.db import models

# Create your models here.

class Item(models.Model):
    product = models.ForeignKey('Company.Product', on_delete=models.CASCADE, related_name='items')
    quantity = models.PositiveIntegerField(default=1)

class Quote(models.Model):
    items = models.ManyToManyField(Item)
    url = models.URLField(blank=True, null=True)
    is_accepted = models.BooleanField(default=False)

class PaymnetPeriod(models.Model):
    time_period = models.DurationField()

class Subscription(models.Model):
    package = models.ForeignKey('Company.Package', on_delete=models.CASCADE, related_name='subscriptions')
    date_started = models.DateTimeField(auto_now=True)
    payment_period = models.ForeignKey(PaymnetPeriod, on_delete=models.CASCADE, related_name='subscriptions')

class Payment(models.Model):
    client = models.ForeignKey('Company.Client', on_delete=models.CASCADE, related_name='payments')
    amount = models.PositiveIntegerField(default=0)
    date = models.DateTimeField(auto_now=True)

core/models.py
from django.db import models

# Create your models here.

website/models.py
from django.db import models

website/forms.py
from django import forms

Company/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, FormView, DeleteView
from .models import *
# Create your views here.
class CompanyHomepage(LoginRequiredMixin, TemplateView):
    template_name = 'company/homepage.html'

    def get_context_data(self, **kwargs):
        employee = Employee.objects.get(user=self.request.user)
        context = {
            'company': employee.company
        }
        return context

Invoice/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, authenticate as auth_authenticate, logout as auth_logout
from django.conf import settings
from django.core.exceptions import SuspiciousOperation

from .utils import recaptcha_validation

# Application Views

# Login
def login(request):
	if (request.method == "POST"):
		if True:
		# if recaptcha_validation(request.POST.get('g-recaptcha-response')):
			form = AuthenticationForm(request, request.POST)
			if form.is_valid():
				username = form.cleaned_data.get('username')
				raw_password = form.cleaned_data.get('password')
				user = auth_authenticate(username=username, password=raw_password)
				auth_login(request, user)
				next_page = request.GET.get('next', 'website:homepage_view')
				return redirect(next_page)
		else:
			raise SuspiciousOperation()
	else:
		form = AuthenticationForm()

	context = {
		'form': form,
		'recaptcha_site_key': settings.RECAPTCHA_SITE_KEY,
	}
	return render(request, 'registration/login_page.html', context)

# Logout
def logout(request):
	auth_logout(request)
	next_page = request.GET.get('next', 'website:homepage_view')
	return redirect(next_page)

website/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.contrib import messages
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
import json

#-------------------------------------------------------------------------------
# Page Views
#-------------------------------------------------------------------------------
@login_required
def homepage_view(request):
    context = {}
    return render(request, "website/homepage.html", context)

Company/templates/company/homepage.html
{% extends 'website/base.html' %}

{% block custom_css %}
<style type="text/css">
td {
  font-size: 20px;
}

th:nth-child(2), th:nth-child(3),
td:nth-child(2), td:nth-child(3) {
  text-align: center;
}
</style>
{% endblock custom_css %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col text-center">
      <h2>{{ company }}</h2>
      </div>
    </div>
    <br/>
    <div class="row">
      <div class="col-md-4 col-sm-12 text-center">
        <table class="table">
          <thead>
            <tr><th colspan="3">Open Quotes</th></tr>
          </thead>
          <tbody>
            {% for quote in company.get_quotes %}
              <tr>
                <td>{{ quote.client }}</td>
                <td>{{ quote.amount }}</td>
                <td>{{ quote.is_accepted|yesno:"Accepted,Pending"}}</td>
              </tr>
            {% empty %}
              <tr>
                <td colspan="3">No quotes yet!</td>
              </tr>
              </tbody>
            </table>
            {% endfor %}
            </div>
            <div class="col-md-4 col-sm-12 text-center">
              <table class="table">
                <thead>
                  <tr><th colspan="3">Invocies</th></tr>
                </thead>
                <tbody>
                  {% for invoice in comapny.get_invoices %}
                    <tr>
                      <td>{{ invoice.client }}</td>
                      <td>{{ invoice.amount }}</td>
                      <td>{{ invoice.get_amount_remaining }}</td>
                    </tr>
                  {% empty %}
                    <tr>
                      <td colspan="3">No invoices yet!</td>
                    </tr>
                    </tbody>
                  </table>
                  {% endfor %}
                </div>
                <div class="col-md-4 col-sm-12 text-center">
                  <table class="table">
                    <thead>
                      <tr><th colspan="3">Services</th></tr>
                    </thead>
                    <tbody>
                      {% for invoice in comapny.get_invoices %}
                      <tr>
                        <td>{{ invoice.client }}</td>
                        <td>{{ invoice.amount }}</td>
                        <td>{{ invoice.get_amount_remaining }}</td>
                      </tr>
                      {% empty %}
                      <tr>
                        <td colspan="3">No invoices yet!</td>
                      </tr>
                    </tbody>
                  </table>
                  {% endfor %}
                </div>
                </div>
                <br/>
                <div clas="row">
                <div class="col-md-12 text-center">
                  <table class="table">
                    <thead>
                      <tr><th colspan="3">Income</th></tr>
                    </thead>
                    <tbody class="table-responsive">
                      {% if chart %}
                      <tr>
                        <td>{{ chart.as_html }</td>
                      </tr>
                      {% else %}
                      <tr>
                        <td colspan="3">No income data yet!</td>
                      </tr>
                      {% endif %}
                    </tbody>
                  </table>
                    </div>
                  </div>

  </div>
{% endblock content %}

website/templates/website/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">


		<title>{% block title %}InvoiceSense{% endblock title %}</title>

		<!-- CSS -->
			<!-- Latest compiled and minified CSS -->
			<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
			<link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}">
			<link rel="stylesheet" href="{% static 'website/css/animate.css' %}"/>
			<link rel="stylesheet" href="{% static 'website/css/style.css' %}"/>
			{% block custom_css %}
			{% endblock custom_css %}

		<!-- JavaScript -->

			<!-- jQuery library -->
			<script src="{% static 'website/js/jquery.min.js' %}"></script>

			<!-- Latest compiled JavaScript -->
			<script src="{% static 'website/js/bootstrap.min.js' %}"></script>

			<script src="{% static 'website/js/main.js' %}"></script>

			<script src="{% static 'website/js/formset.js' %}"></script>

			{% block head_js %}
			{% endblock head_js %}
			<link rel="shortcut icon" href="{% static 'website/images/logo.jpg' %}" />
			<link href="https://fonts.googleapis.com/css?family=Roboto:100" rel="stylesheet">
			<style type="text/css">
				body {
				  background: url("{% static 'website/images/bg.jpg' %}") no-repeat center center fixed;
				  -webkit-background-size: cover;
				  -moz-background-size: cover;
				  -o-background-size: cover;
				  background-size: cover;
				  font-family: 'Roboto', sans-serif;
				  font-weight: bold;
				  overflow-x: hidden !important;
				}
			</style>
	</head>
	<body>

		<div id="page-container">

			<div id="content-wrap">
				{% include 'website/navbar.html' %}
				{% block content %}
				{% endblock content %}
			</div>

			<div id="footer">
				<div class="row">
					<div class="col" style="margin-top:10px;">
						<h5><b>Created By</b></h5>
						<h6>Tech and Mech USA</h6>
					</div>
					<div class="col">
						<i class="fab fa-facebook-square"></i>
						<i class="fab fa-youtube"></i>
						<i class="fab fa-linkedin"></i>
						<i class="fab fa-twitter-square"></i>
						<i class="fab fa-instagram"></i>
					</div>
					<div class="col" style="margin-top:10px;text-align:right;">
						<text style="position:relative;top:3px;margin-right:10px;">© 2019 Tech and Mech USA LLC</text>
						<img class="footer-img" src="{% static 'website/images/logo.jpg' %}">
					</div>
				</div>
			</div>

		</div>

		{% block js %}
		{% endblock js %}
	</body>
</html>

website/templates/website/homepage.html
{% extends 'website/base.html' %}

{% block custom_css %}
{% endblock custom_css %}

{% block content %}
{% include 'website/server_messages.html' %}
<div class="container"></div>
{% endblock content %}

{% block js %}
<script>
</script>
{% endblock js %}

website/templates/website/js/functions.html
<script>
</script>

website/templates/website/navbar.html
{% load staticfiles %}

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="{% url 'website:homepage' %}">
    <img id="logo" src="{% static 'website/images/logo.jpg' %}" alt="Logo" style="width:40px;">
  </a>

  <!-- Brand -->
  <a class="navbar-brand" href="{% url 'website:homepage' %}">
    <b>T & M <text class="color-primary">USA</text></b><br />
    InvoiceSense
  </a>

  <!-- Links -->
</nav>

website/templates/website/server_messages.html
<!-- Server Messages to User -->
<div class="row">
  {% block custom_message %} {% endblock custom_message %}
  <div class="col center">
    {% if messages %}
        {% for message in messages %}
            {% if "error" in message.level_tag %}
            <div class="alert alert-warning">
                <text {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </text>
            </div>
            {% else %}
            <div class="alert alert-success">
                <text {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </text>
            </div>
            {% endif %}
        {% endfor %}
    {% else %}
    <br />
    {% endif %}
  </div>
</div>